### PR TITLE
Update Travis build matrix to include Rails 5.

### PR DESCRIPTION
**Pull request by saghaulor**

### CODE REVIEW

**Comment by connorshea** [comment]
You need at least 2.2.2 for ActiveRecord 5, that'll fix one of the tests

**Comment by connorshea** [comment]
`silence_stream` has been removed in 5.0: https://github.com/rails/rails/commit/481e49c64f790e46f4aff3ed539ed227d2eb46cb

That's the reason for the failure on ActiveRecord 5.

**Comment by connorshea** [comment]
More info on the Kernel methods being deprecated:

https://github.com/rails/rails/compare/1fbb5c1873a1...3121412cf181

https://github.com/rails/rails/pull/13392

**Comment by saghaulor** [comment]
Thanks for looking into the failures @connorshea

**Comment by connorshea** [comment]
@saghaulor Been doing way too much Rails 5 research, so this was pretty easy for me :P

See https://gitlab.com/gitlab-org/gitlab-ce/issues/14286#note_12833875 for a lot of the deprecations/removals in 5.0, might be useful to prevent problems once 5.1 comes around :)

**Pull request merged**
