### PR TITLE
Fix for set_attribute_was patch issue and Rails 7 support

### PR DESCRIPTION
**Pull request by vimalvnair**
This fixes the issue mentioned in PR: https://github.com/attr-encrypted/attr_encrypted/pull/431 , created by @mvastola

I am using the `write_cast_value` method from ActiveModel instead of the removed `set_attribute_was` to manage virtual attributes. This will work for Rails version 5.2 and higher. I locally ran the tests for all the rails versions mentioned in travis.yml and the tests are passing for all. I couldn't find a way to push the fix to the above PR, some I am creating a new one.

I have tested the fix with our internal app and have not encountered any issues. However, I recommend that others also test it with their applications. 

I have also included the changes for Rails 7 support which fixes https://github.com/attr-encrypted/attr_encrypted/issues/423 . These changes were taken from PR: https://github.com/attr-encrypted/attr_encrypted/pull/425, created by @movermeyer. I couldn't find a way to contribute to that. I suggest reviewing the PR and the conversations there for additional context.

After these changes `attr_encrypted` should start working with Rails 7

### CODE REVIEW

**Comment by vimalvnair** [comment]
The checks are failing for only Ruby 2.6.10. Caused by: 
```
sqlite3-1.6.1-x86_64-linux requires ruby version >= 2.7, < 3.3.dev, which is
incompatible with the current version, ruby 2.6.10p210
```

Tests for all versions of Rails, with Ruby 2.7.6 are passing in Travis

**Comment by vimalvnair** [comment]
sqlite3 v1.6.0 and above removed the native gem support for ruby 2.6: https://github.com/sparklemotion/sqlite3-ruby/pull/367 . So I am hardcoding the sqlite3 version to 1.5.4 in `gemspec`. 

We can also think about dropping the support for ruby 2.6

All the tests are passing now.

cc: @joshbranham @mvastola

**Comment by joshbranham** [comment]
Thanks @vimalvnair this looks great to me. @mvastola any concerns?

**Comment by mikevoets** [comment]
When this gets merged (hopefully soon 🎉 ), will this be packaged into a release right after? :-)

**Review by joshbranham — APPROVED** [review]

**Review by mvastola — APPROVED** [review]
LGTM. Thanks for doing this, all!

**Comment by vimalvnair** [comment]
Thank you @mvastola @joshbranham for looking into this.

**Comment by vimalvnair** [comment]
@mvastola @joshbranham Can we also package this into a release?

**Comment by joshbranham** [comment]
Resolves https://github.com/attr-encrypted/attr_encrypted/pull/425

@vimalvnair working on it in https://github.com/attr-encrypted/attr_encrypted/pull/435

**Pull request merged**
