### PR TITLE
Use Github Actions for CI

### PR DESCRIPTION
**Pull request by mlarraz**
Link to build on my fork: https://github.com/mlarraz/attr_encrypted/actions/runs/4798509264/

Not sure what the current story is with Travis, but Github Actions is free and starts quickly.

### CODE REVIEW

**Comment by joshbranham** [comment]
> Link to build on my fork: https://github.com/mlarraz/attr_encrypted/actions/runs/4798509264/
> 
> Not sure what the current story is with Travis, but Github Actions is free and starts quickly.

I was open to switching to Github Actions as well, but just haven't prioritized it. When we started contributing, @mvastola reached out to Travis to get credits added. Given that process is manual and time delayed, I would vote to switch to GitHub Actions.

Note: We should probably keep the ActiveRecord 5.x testing if it's not too complicated, given folks out there likely still running that. Happy to discuss removing it in another PR down the line.

**Comment by mlarraz** [comment]
Rails 5.1 and 5.2 are not compatible with Ruby 3, so I will have to exclude those combinations from the build matrix if you plan to keep support

**Comment by joshbranham** [comment]
> Reference in new

Yup I did that as well for Travis here https://github.com/attr-encrypted/attr_encrypted/pull/440

**Comment by joshbranham** [comment]
@mvastola I am in favor of dropping Travis for GitHub Actions as well. Let me know your thoughts, if so we can merge this and close https://github.com/attr-encrypted/attr_encrypted/pull/440

**Review by mvastola — APPROVED** [review]
@joshbranham I don't have much experience with GitHub actions. I wouldn't mind staying on Travis, but if you think it'd be better to switch, you have my sign-off.

**Comment by mvastola** [comment]
@joshbranham wait, is there an issue with our credits? It looks like this ran on Travis 3 days ago. FWIW, they said something about automatic credits (I'd have to dig up the email). This project had just lapsed for so long they were hesitant to give us any. The way we left off I'm pretty sure they suggested automatic credits were likely if we stay active.

Anyway, I'm deferring to you. Just approved this so you're able to merge should you deem it prudent.

**Comment by joshbranham** [comment]
> @joshbranham wait, is there an issue with our credits? It looks like this ran on Travis 3 days ago. FWIW, they said something about automatic credits (I'd have to dig up the email). This project had just lapsed for so long they were hesitant to give us any. The way we left off I'm pretty sure they suggested automatic credits were likely if we stay active.
> 
> Anyway, I'm deferring to you. Just approved this so you're able to merge should you deem it prudent.

There isn't a current issue with credits, I'm just saying GitHub actions is free for open source and pretty defacto these days.

**Pull request merged**
