### PR TITLE
Fix activerecord adapter when bootstrapping

### PR DESCRIPTION
**Pull request by saghaulor**

### CODE REVIEW

**Comment by saghaulor** [comment]
@tamird Please review.

These changes fix the bootstrapping issue that you rightly raised. Additionally, they revert the hackery that I did to the legacy test harness while still preserving the changes that you made to update the test harness.

**Comment by tamird** [comment]
LG! left a comment about some trailing newlines on the commit but otherwise great. Thanks for fixing this!

**Comment by saghaulor** [comment]
@tamird It looks like the new lines were from the original state of the test files before I moved everything around.

**Comment by tamird** [comment]
sure, might still be nice to remove them. your call.

**Comment by saghaulor** [comment]
@tamird I think I'll leave it per http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline.

I normally strip them but apparently it's there for a reason.

**Comment by tamird** [comment]
nah, you have two newlines there, not one

**Comment by saghaulor** [comment]
:disappointed:

**Comment by saghaulor** [comment]
Perhaps I'm decaffeinated but I only count one new line per file. If there's two I'll definitely remove the second.

**Comment by tamird** [comment]
https://github.com/coupa/attr_encrypted/pull/2

**Comment by tamird** [comment]
:shipit:

**Pull request merged**
