### PR TITLE
Add before_encrypt hook

### PR DESCRIPTION
**Pull request by bglusman**
Originally opened as https://github.com/attr-encrypted/attr_encrypted/pull/248 but will close that in preference of this version with a cleaner interface for clients to set up a hook to have unencrypted value passed into.  Let me know if any changes desired.

### CODE REVIEW

**Comment by bglusman** [comment]
@saghaulor there's just one failure which looks unrelated/like a flicker to me, problem installing a gem...  pretty sure on re-run it will be fine, but if you want me to add some kind of specs for this lmk, wanted approval on the shape and intention/willingness to merge before spending more time on it.

**Comment by bglusman** [comment]
@saghaulor or anyone? ( @austintaylor / @sbfaulkner maybe?) ping?

**Comment by saghaulor** [comment]
@bglusman I'm not sure I understand the intent. Moreover, I'm suspicious of code changes that aren't accompanied by tests.

**Comment by bglusman** [comment]
@saghaulor happy to add tests, wanted buy in first, though we're already using this in production I think on a fork.  The intent is, for example, in our use case, being able to find encrypted email addresses without having to encrypt them insecurely.  We add a hook on save to update a column with a sha1 hash of the cleartext, so instead of searching for the encrypted data (which we want to have different IV every time, though not necessarily different salt), we search the hash column for a hash of the cleartext.  This is both for finding on login, and for ensuring no duplicate emails in the system.

**Pull request closed without merging**
