### PR TITLE
5.1 wants virtual attributes to be marked

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/attr-encrypted/attr_encrypted/issues/260

### CODE REVIEW

**Comment by grosser** [comment]
@saghaulor

**Comment by saghaulor** [comment]
@grosser does it make sense to have this in Rails 5 as well? Isn't that where the Attributes API was introduced? 

Also, is there a way test this?

**Comment by grosser** [comment]
- updated and made it fail on deprecations ... so when removing the patch it will blow up and we won't use deprecated features in the future
 - 5.0 fails when using attribute api and does not show deprecations, so should be fine

... good to go ?

**Comment by timhaines** [comment]
@saghaulor would love to see this merged and released.  👍

**Comment by fotinakis** [comment]
Same here, would love to see this get out!

**Comment by saghaulor** [comment]
I'll try to push a new version soon. I was hoping to do a major release at some point. I'll need to revisit the merged changes to see if they warrant a major version bump or not.

**Comment by f3ndot** [comment]
@saghaulor hate to be that person, but will the release be cut soon?

**Comment by mauro-oto** [comment]
@saghaulor could you release a new patch or minor version with this fix? We're getting flooded with deprecation warnings which are solved by it. Thank you very much for your work!

**Comment by tejasmanohar** [comment]
@saghaulor sorry to bother, but would you please issue a release? thanks for all your work so far and any in the future!

**Comment by garettarrowood** [comment]
@saghaulor - We are also getting flooded with deprecation warnings at my workplace. Would it be possible to cut a release? Thanks for this great gem!

**Comment by grosser** [comment]
try reaching out to some of the other gem owners https://rubygems.org/gems/attr_encrypted

**Comment by garettarrowood** [comment]
cc/ @smhuber , @sbfaulkner , & @billymonk

**Comment by sbfaulkner** [comment]
sorry, but the three of us have had next to nothing to do with this gem in some time... perhaps @saghaulor would welcome someone who is willing to continue helping to maintain

**Pull request merged**
