### PR TITLE
remove alias_method_chain to get rid of rails 5 deprecations

### PR DESCRIPTION
**Pull request by grosser**
@saghaulor @sblackstone

lazy ass version of https://github.com/attr-encrypted/attr_encrypted/pull/213 ... but it works and won't break anything ... so merge this first and then if anyone cares refactor to prepend ?

### CODE REVIEW

**Comment by sblackstone** [comment]
+1!  I'll try to re-work the other at some point..

**Comment by grosser** [comment]
@saghaulor mind hitting merge ?
alternatively add me as maintainer and I'lll take care of it ...

**Comment by saghaulor** [comment]
Thanks for working on this @grosser and @sblackstone

**Comment by grosser** [comment]
you might have to merge again ... gh is messed up right now :D

**Comment by grosser** [comment]
so I guess adding a comment expires their cache ...

**Comment by grosser** [comment]
can you release a new version too ?

FYI getting jenkins build errors in my mail ... can you turn these off ?

```
s <interactive.alerts@mosaic.com>
8:42 AM (30 minutes ago)

to michael, saghaulor, jean.boussier 
See <http://jenkins.mssvirt.com/job/attr_encrypted/ACTIVERECORD=4.0.0,rubyversion=2.0.0/62/changes>

Changes:

[michael] remove alias_method_chain

------------------------------------------
[...truncated 1443 lines...]
    <http://jenkins.mssvirt.com/job/attr_encrypted/ACTIVERECORD=4.0.0,rubyversion=2.0.0/ws/lib/attr_encrypted.rb>:259:in `encrypt'
    <http://jenkins.mssvirt.com/job/attr_encrypted/ACTIVERECORD=4.0.0,rubyversion=2.0.0/ws/lib/attr_encrypted.rb>:293:in `method_missing'
    <http://jenkins.mssvirt.com/job/attr_encrypted/ACTIVERECORD=4.0.0,rubyversion=2.0.0/ws/test/legacy_attr_encrypted_test.rb>:99:in `test_should_encrypt_email'

 74) Error:
LegacyAttrEncryptedTest#test_should_decrypt_utf8_with_encoding:
NotImplementedError: authenticated?() function is unimplemented on this machine
    /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p353/gems/encryptor-3.0.0/lib/encryptor.rb:86:in `authenticated?'
    /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p353/gems/encryptor-3.0.0/lib/encryptor.rb:86:in `crypt'
    /var/lib/jenkins/.rvm/gems/ruby-2.0.0-p353/gems/encryptor-3.0.0/lib/encryptor.rb:36:in `encrypt'
    <http://jenkins.mssvirt.com/job/attr_encrypted/ACTIVERECORD=4.0.0,rubyversion=2.0.0/ws/lib/attr_encrypted.rb>:259:in `encrypt'
```

**Comment by twe4ked** [comment]
I'd love a release with these changes. Thanks :)

**Comment by grosser** [comment]
@sblackstone please release!

**Pull request merged**
