### PR TITLE
Stop testing EOLed ruby versions in Travis

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there and thank you for maintaining this project! ❤️ 

Right now the Ruby versions that have not EOLed are:

- 2.4
- 2.5
- 2.6
- 2.7

I was hoping that this PR will make it easier to maintain the gem from now on. 

Please check it out.

Thanks!

### CODE REVIEW

**Comment by etagwerker** [comment]
@saghaulor @ankane I realize this is quite an opinionated way to go about this: dropping support for EOLed versions of Rails and Ruby. I'd really like to know your thoughts about this and offer a helping hand moving some of the PRs forward. 😄

**Comment by etagwerker** [comment]
@saghaulor @ankane Do you think this is a step in the right direction? Anything I can do to help with this PR?

**Comment by ankane** [comment]
@etagwerker I'm not a member of the project, but seems reasonable to me

**Comment by etagwerker** [comment]
@saghaulor Did you get a chance to see this? Do you think it is a good idea? 😸

**Comment by saghaulor** [comment]
@etagwerker thanks for contributing. I apologize for the radio silence, life has caught up with me.

 I've been trying to maintain backwards compatibility because I'm aware that there's a few companies that are running very old stacks, so I was hoping to give them an easy upgrade path. However, I do understand that this adds cruft to the code. Perhaps dropping very old versions is something we should do. I mean they simply only have to upgrade the gem to support newer versions of the stack.

If we're going to officially drop support, we should also drop the code that supports the older versions of Rails/Ruby. If you're not feeling up to doing that, perhaps we can do it in another PR and then merge this one after that one.

**Comment by joshbranham** [comment]
Thanks for this @etagwerker I am going to close it as this was resolved in https://github.com/attr-encrypted/attr_encrypted/commit/d92e8c2cf27988bce9d55629117553c1f3a90686 via a bigger change.

**Pull request closed without merging**
