### PR TITLE
Modernize and cleanup

### PR DESCRIPTION
**Pull request by tamird**
Cleanup extracted from #115

### CODE REVIEW

**Comment by tamird** [comment]
This is green @billymonk @saghaulor

**Comment by saghaulor** [comment]
@tamird Please squash your commits and I'll be happy to merge.

**Comment by tamird** [comment]
They look pretty clean to me. Why squash?

**Comment by saghaulor** [comment]
@tamird I generally follow a workflow where a feature is squashed to a single commit. This helps to during git bisecting. It's not a big deal though. Thanks for putting in the work to modernize the gem!

**Pull request merged**
