### PR TITLE
Ar any order

### PR DESCRIPTION
**Pull request by tamird**
@billymonk The separate PR requested in #137

### CODE REVIEW

**Comment by tamird** [comment]
hi, would someone take a look at this please? /cc @saghaulor

**Comment by saghaulor** [comment]
@tamird this code seems to already be merged into master. (https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted/adapters/active_record.rb#L28) However, I don't understand that the intent is. Furthermore, it seems to have broken behavior for me. I am still trying to find the exact issue but I have narrowed down the problematic code to this code change in master.

Can you please elaborate on the problem that you're trying to solve, as well as what the solution is supposed to do? cc @billymonk

**Comment by tamird** [comment]
@saghaulor the original code came with a test case (https://github.com/attr-encrypted/attr_encrypted/commit/c080191617f9db3ef92696e6a5170d1b130c3112)  which illustrates the intent.

There's still one unmerged commit here that has its own test case -- can we merge that?

**Comment by saghaulor** [comment]
@tamird Thanks for replying. I reviewed your test case and I didn't find the intent obvious. Can you please elaborate? 

As this change has affected me, I'm forced to remove it from my software via our own fork of attr_encrypted. However, I would very much like to use the official version and to preserve old behavior.

Lastly, I'm not an official maintainer, though I am very intimately familiar with the gem as I have been working with it for the last year and a half. On that note, the travis build appears to be broken. The maintainers should not merge until you have resolved those issues.

**Comment by tamird** [comment]
Travis is broken because of upstream changes to i18n, which is not related to the changes in this branch.

What broken behaviour are you observing? Can you illustrate with a test case?

**Comment by saghaulor** [comment]
@tamird I am trying to pinpoint the failure so that I may illustrate with a test case. Can you please explain the intent?

**Comment by tamird** [comment]
The previous behaviour would always stringify attribute keys, so the case:
```
def test_should_preserve_hash_key_type
  hash = { :foo => 'bar' }
  account = Account.create!(:key => hash)
  assert_equal account.key, hash
end
```
is asserting against the previous behaviour which was:
```
def test_should_preserve_hash_key_type
  hash = { :foo => 'bar' }
  account = Account.create!(:key => hash)
  assert_equal account.key, { 'foo' => 'bar' }
end
```

**Comment by billymonk** [comment]
@saghaulor, if that change broke behaviour on your end then that's on me. It passed tests and worked for a small app I keep to test the gem against but you're clearly using it a lot harder than I test it. 

Obviously we're missing a test case so it would be great if you provided one one that demonstrates breakage.

Based on how it broke for you we can go from there.

**Comment by saghaulor** [comment]
@billymonk @tamird just to be clear I'm not trying to point fingers. I wanted to raise the fact that there is an issue, that I'm trying to collect more info, and that I didn't understand the original intent of the change. 

I wanted to understand it so that a) I can see if it's something that I'm doing on my end, and b) if it is an issue with the gem, if I can come to a solution that addresses the issue but maintains old behavior. 

As soon as I get can pinpoint what is happening, I'll try to codify the behavior in a test so that we can get to the bottom of this.

Lastly, thank you to both of you for replying so quickly.

**Comment by billymonk** [comment]
No of course not @saghaulor, don't worry. Simply saying that I didn't do the proper due diligence if something did break. 

Yes, please do whatever you have to find the issue. 

Thanks

**Pull request merged**
