### PR TITLE
Rails 7 support

### LINKED ISSUE #423: Undefined method `#key?` for nil:NilClass
This method crashes on `self.class.encrypted_attributes.key?`.

```ruby
def perform_attribute_assignment(method, new_attributes, *args)
  return if new_attributes.blank?

  send method, new_attributes.reject { |k, _|  self.class.encrypted_attributes.key?(k.to_sym) }, *args
  send method, new_attributes.reject { |k, _| !self.class.encrypted_attributes.key?(k.to_sym) }, *args
end
```

I was using this in a migration when I got this issue.

### PR DESCRIPTION
**Pull request by movermeyer**
### What are you trying to accomplish?

Fixes #423.

Rails 7 introduced [Active Record Encryption](https://edgeguides.rubyonrails.org/active_record_encryption.html), which has names that collide with the names that `attr_encrypted` is using.

### What approach did you choose and why?

I took over @ryosk7, @kineca, and @armiiller's [closed PR](https://github.com/attr-encrypted/attr_encrypted/pull/400), rebased it on latest `master`, and recreated it here.

It's a simple rename of class variables and methods, adding a `attr_encrypted_` prefix to each.

IMO, it's a perfectly cromulent rename.

### What should reviewers focus on?

This is a breaking change, since anyone relying on these names will have to update their code.

### The impact of these changes

`attr_encrypted` will work once again on Rails 7

### CODE REVIEW

**Comment by xjunior** [comment]
Can you add rails 6 and 7 to the [test matrix](https://github.com/attr-encrypted/attr_encrypted/blob/master/.travis.yml)?

**Comment by xjunior** [comment]
I think we'll need a smarter matrix. Rails 7 isn't compatible with ruby <3.1.

**Comment by movermeyer** [comment]
> I think we'll need a smarter matrix. Rails 7 isn't compatible with ruby <3.1.

Also might be a good time to migrate to GitHub Actions?

**Comment by movermeyer** [comment]
Also, it seems that `set_attribute_was` was removed in Rails 6.

**Comment by jayakrishnang** [comment]
Hi @movermeyer, is there any workaround that you suggest we could try here?

**Comment by TheStranjer** [comment]
For what it's worth, this at least appears to work.

**Comment by jayakrishnang** [comment]
True, we could probably look at this patch to fix the `set_attribute_was` situation.
https://github.com/salsify/attr_encrypted/pull/1

**Comment by mdh** [comment]
> I think we'll need a smarter matrix. Rails 7 isn't compatible with ruby <3.1.

From what I can see >= 2.7 is fine:
https://github.com/rails/rails/blob/v7.0.4/rails.gemspec#L12

**Comment by joshbranham** [comment]
I was working with @mvastola but have been a bit busy. The idea was to cut a new major release for this breaking change and let rails 7 users upgrade. There is some discussion around how much we should maintain previous versions of this library for older Ruby and ActiveRecord versions. Fwiw we are using this exact patch on a fork at my company to get onto Rails 7, then figuring out how to migrate the data and move to native Rails encryption.

**Comment by joshbranham** [comment]
> True, we could probably look at this patch to fix the `set_attribute_was` situation. https://github.com/salsify/attr_encrypted/pull/1

I am working to pull that in here https://github.com/attr-encrypted/attr_encrypted/pull/427

**Comment by guillaumebriday-pa** [comment]
> I was working with @mvastola but have been a bit busy. The idea was to cut a new major release for this breaking change and let rails 7 users upgrade. There is some discussion around how much we should maintain previous versions of this library for older Ruby and ActiveRecord versions. Fwiw we are using this exact patch on a fork at my company to get onto Rails 7, then figuring out how to migrate the data and move to native Rails encryption.

Hi @joshbranham! First, thanks for your awesome work 👍 

Do you have any idea when this could be released, to upgrade to Rails 7?

Thanks

**Comment by joshbranham** [comment]
The current blocker is `set_attribute_was` doesn't work in >= 6 Activerecord. In removing it's support, some of the tests now fail per https://github.com/attr-encrypted/attr_encrypted/pull/431

I haven't had much luck understanding why those tests exist, and if anyone is using `#attr_was` style methods via `attr_encrypted`. I assume they are, but the way this all works feels brittle. So if you wanted to take a look at that, we could get tests passing and merge this and then you could at minimum use the commit off `master`.

**Pull request closed without merging**
