### PR TITLE
Add support for mongoid

### PR DESCRIPTION
**Pull request by billymonk**

### CODE REVIEW

**Comment by gildegoma** [comment]
Sorry to comment again, but I've just realized (too late) that although @billymonk is member of @attr-encrypted organization, I'd better direct poke @saghaulor to ask if this addition proposal could be reactivated... Thank you all for your understanding, and this nice project :heart:

**Comment by HLFH** [comment]
@gildegoma Use this: https://github.com/rocketjob/symmetric-encryption

**Comment by gildegoma** [comment]
@HLFH I hear you, especially because I've started yesterday to evaluate these two gems (symmetric-encryption vs attr_encrypted). So far, attr_encrypted does very well the job (as well).

PS: I don't want to hijack this issue/thread, so I invite you to continue the discussion on another channel (e.g. twitter, or alike). I'm very curious to know why your recommend to use symmetric-encryption (without any details :wink:)

**Comment by saghaulor** [comment]
@gildegoma It's something that we can explore. I'm all for adding more ORMs into the mix. I don't have any experience with Mongoid so I'm open to new contributions.

**Pull request closed without merging**
